import Image from "next/image";
import Bullet from "devextreme-react/bullet";

export default function Home() {
  return (
    <table>
      <tbody>
        <tr>
          <td>
            <Bullet
              className="bullet"
              width={200}
              startScaleValue={0}
              endScaleValue={100}
              value={30}
              target={50}
              color={"blue"}
            />
          </td>
        </tr>
        <tr>
          <td>
            <Bullet
              className="bullet"
              width={200}
              startScaleValue={0}
              endScaleValue={100}
              value={30}
              target={50}
              color={"blue"}
            />
          </td>
        </tr>
        <tr>
          <td>
            <Bullet
              className="bullet"
              width={200}
              startScaleValue={0}
              endScaleValue={100}
              value={30}
              target={50}
              color={"blue"}
            />
          </td>
        </tr>
        <tr>
          <td>
            <Bullet
              className="bullet"
              width={200}
              startScaleValue={0}
              endScaleValue={100}
              value={30}
              target={50}
              color={"blue"}
            />
          </td>
        </tr>
        <tr>
          <td>
            <Bullet
              className="bullet"
              width={200}
              startScaleValue={0}
              endScaleValue={100}
              value={30}
              target={50}
              color={"blue"}
            />
          </td>
        </tr>
        <tr>
          <td>
            <Bullet
              className="bullet"
              width={200}
              startScaleValue={0}
              endScaleValue={100}
              value={30}
              target={50}
              color={"blue"}
            />
          </td>
        </tr>
        <tr>
          <td>
            <Bullet
              className="bullet"
              width={200}
              startScaleValue={0}
              endScaleValue={100}
              value={30}
              target={50}
              color={"blue"}
            />
          </td>
        </tr>
      </tbody>
    </table>
  );
}
